### ISSUE TITLE
changing user password error

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#135]
When I try to change my login password for the manager I get the error "ERROR: empty key detected!".
But the process still continues, everything ends fine.(I tried my own installation and the test-platform on sourceforge)

**Comment by BenjaminHae** [comment]
I think the problem is 
`"fname": encryptchar(accountarray[x]["fname"],newsecretkey)`
when `fname` is empty. The line can probably just be deleted, but as I have no idea how the file things work I'm not sure.

**Comment by zeruniverse** [comment]
I'll take a look.

On Sun, Mar 12, 2017 at 9:16 AM Benjamin Häublein <notifications@github.com>
wrote:

I think the problem is
"fname": encryptchar(accountarray[x]["fname"],newsecretkey)
and it can probably be just deleted. But as I have no idea how the file
things work I'm not sure.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zeruniverse/Password-Manager/issues/135#issuecomment-285955164>,
or mute the thread

**Comment by zeruniverse** [comment]
Yes, it's caused by empty `fname`. Quite strange that I didn't encounter into the problem yet...
