### ISSUE TITLE
v9.15 test

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#158]
We introduced a lot of problems in v9.13 (e.g. not able to export csv & raw file). We should make sure the new v9.15 (HEAD of master branch) is production ready.

I've run the whole test once. It would be great if you can check it again (and with the plugin).

**Comment by zeruniverse** [comment]
Sometimes, after login, the screen shows DECRYPTING YOUR PASSWORDS but automatically log you out after 1~2 seconds. The error msg is AUTHENTICATION ERROR.

**Comment by BenjaminHae** [comment]
Tomorrow I'll have time to setup a test environment then I can test more intrusive things like importing or changing the login password.
I haven't seen the error you described yet.

**Comment by BenjaminHae** [comment]
I have found two minor issues in the manager and one in the browser addon. Should I track the ones for the manager here or in my fork?
I think I'll have time to fix them tomorrow.

About the csv-import: Maybe we could also move that to recovery? And use that to turn it into a .raw file? That could also fix one of the issues I found.

**Comment by zeruniverse** [comment]
I think no. That makes the first use more complicated and users will stop using this software. It is a fatal fault in software development.

**Comment by BenjaminHae** [comment]
oh yes. good point.

**Comment by BenjaminHae** [comment]
Ok, the last possible error I found is this: When you import from `csv` only defined user fields are being imported. So everything starting with a `_` is not.

I've thought about it for some time, but now I believe it should stay that way. When somebody uses `csv` import it's reasonable to assume the `csv` was not generated by this password manager. So we probably couldn't interpret things like the password age correctly. Ergo we shouldn't import it.

What do you think?

**Comment by zeruniverse** [comment]
This is intentionally designed like this. Because _value is system
variables. if imported from .raw, _values will be there.

**Comment by BenjaminHae** [comment]
Alright then I'm finished testing.

**Comment by zeruniverse** [comment]
Great!

**Comment by BenjaminHae** [comment]
Oh, just found a conceptual thing we should talk about:

`pbkdf2` is only executed on the client side. That means mostly the attackers hardware determines the speed of his password guessing. While the 1000 rounds take a few seconds for us, an attacker can easily do one guess in about 0.002s(I tested it on a not so fast server).
So if we execute the pbkdf2 on the server(additionally to on the client) we determine the speed of the attackers guesses. (I'm disregarding brute-force preventions here).

Owasp currently recommends 64000 rounds so that even when the database is compromised guessing the passwords isn't feasible. 64000 rounds on the client are just not practical.

I'd like to implement this, but: It's only doable if we remove `'random_login_stamp'`. I think it's okay to remove it, because since 9.13 we only support connections over tls, so we shouldn't be afraid of replay attacks.

**Comment by zeruniverse** [comment]
Yes. You can remove it.

Thank you for this.
