### ISSUE TITLE
login error : after signup

### ISSUE THREAD

**Issue by w112nxs** [zeruniverse/Password-Manager#184]
Created a record successfully via signup. verified checking DB as well. But login fails with authentication failure.

Noticed the entry in the records show with characters in salt column. I'm I missing anything on my install - any php modules etc?
 
|  1 | test | 5caeee36caaa384cc6d9150360565b736549ac690a22fe270c1926a1c80d1d7f | xr�0����T4�k)41�{�x��Ռ | {"url":{"colname":"URL","hint":"","cls":" hidden"},"user":{"colname":"Username","hint":"","cls":" hidden-xs","position":1},"comment":{"colname":"Comment","hint":"","cls":" hidden","type":"textarea"},"tags":{"colname":"Tags","hint":"Comma separated values","cls":" hidden-xs"}} | abcdef@gmail.com |

**Comment by zeruniverse** [comment]
1. Please download from [release](https://github.com/zeruniverse/Password-Manager/releases) instead of master branch for your own use.

2. Please try our test server https://phppasswordmanager.sourceforge.io/

If your error can be reproduced there, we can figure it out much faster. Otherwise, you might have some issue installing the software. Installation steps are here: https://github.com/zeruniverse/Password-Manager/wiki/Installation

**Comment by w112nxs** [comment]
using the release 9.15 release.
I'm assuming its due to some missing module or library.
the record gets created like i said before with some corrupted or weird vale like shown above.

Assuming its something missing with my environment... can u provide list of php modules that are required.

**Comment by zeruniverse** [comment]
It should not depend on any modules.

**Comment by w112nxs** [comment]
will try a reinstall and update.

**Comment by zeruniverse** [comment]
Please try demo first to see whether the error can be reproduced

**Comment by w112nxs** [comment]
resolved with the following step
 localhost in mysql connection under config.php wasn't working well - added the IP to resolve it.(alternately, you can add a /etc/hosts entry to resolve it too)

**Comment by zeruniverse** [comment]
Could you paste your `config.php` in this issue? If localhost is a general issue, I can make a note
