### ISSUE TITLE
Login failed: AUTHENTICATION ERROR, PLEASE RELOGIN

### ISSUE THREAD

**Issue by dhqcz** [zeruniverse/Password-Manager#193]
Hello. Thank you for your nice project.
I installed newest version and after registration I can't login. After writing login and password it login me for a second (can see "PLEASE WAIT WHILE WE ARE DECRYPTING YOUR PASSWORD") and then it redirect me to login page with alert: "Login failed: AUTHENTICATION ERROR, PLEASE RELOGIN". I tried different browsers & clearing cache. I tried to write login & password 10 times but still the same problem.
PHP version 7.1
Where can the problem be please?

**Comment by zeruniverse** [comment]
Most error occurs due to not following the installation wiki. Please make
sure you did everything here:
https://github.com/zeruniverse/Password-Manager/wiki/Installation

And make sure you are not using master branch (it’s a development branch).

And make sure $HOSTDOMAIN is properly set (must match the link you’ll input
to your browser)

Let me know if you still have problem with all the steps done

Thank you

**Comment by dhqcz** [comment]
Thank you for fast reply. Sorry, it was really my mistake, I forgot to edit $HOSTDOMAIN. Thank you for your great work!

**Comment by BenjaminHae** [comment]
I'll add a fix to index.php for checking if the domain is correct.
