### ISSUE TITLE
Can't import from version 8.01

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#22]
I make a backup, do the restore routine and save the file `raw_pass.txt` - all in version 8.01.
When I reimport this file into the new version I get 

```
aes.js:10 Uncaught Error: Malformed UTF-8
 dataw.Utf8.stringify @ aes.js:10
 decryptchar @ password.js:93
 process @ password.php:344
```

if I try again in the same window I additionally get 

```
one of account or password empty! will continue to process other accounts, check back after this finished
```

and afterwards the same error.

**Comment by zeruniverse** [comment]
Ouch! I forgot this issue! This problem is caused by commit 5f6bb49f2016f4c0bf2c60906a6c3672943a3884 since AES encrypted string format is changed.

I have no good idea to solve the problem for now... Maybe you need to take a screenshot of your old passwords and input them manually in the new version again.

Maybe csv export should be implemented in the next version so such problem won't happen in the  future.

**Comment by zeruniverse** [comment]
If you already deleted the old version, you can try to put v8.01 into some folder in your server. You don't need to change the database, just go to `path/recovery.php` and recover the passwords. Then you can take a screenshot of them...

**Comment by BenjaminHae** [comment]
The old version is still installed. I think I will implement a csv export for me. This should be the easiest way.

P.S: Sorry for the error when changing passwords. Seems like I didn't test thoroughly enough.

**Comment by zeruniverse** [comment]
No worries. I've updated the upgrade steps in README. And I'll implement csv export in 9.01
