### ISSUE TITLE
Extra table td before username

### ISSUE THREAD

**Issue by gwmedia** [zeruniverse/Password-Manager#245]
Not really an issue, just a question about putting an extra td (normal field) before the username/password fields... Where do i do this?

I am pretty new to this, but this system is awesome.

**Comment by BenjaminHae** [comment]
After logging in, look under settings "customize fields". A good example is the"user" field copy it and modify it as you desire. 
But please copy the original value of the json string as a backup. Because if you break the syntax in the definition of fields, nothing will load anymore. In the worst case you will have to reset this string in the database (this is currently one of the few values not stored encrypted).

**Comment by zeruniverse** [comment]
Yes, please use the "customize fields" field in the setting. This way you don't have to implement anything in the backend and you are sure everything is encrypted.

**Comment by gwmedia** [comment]
Is it possible to use the customize fields setting to put it in front of username and password?

couldnt find that ;)

**Comment by BenjaminHae** [comment]
I think the username field uses the position parameter.  You can use that parameter in your custom fields.

**Comment by gwmedia** [comment]
> I think the username field uses the position parameter. You can use that parameter in your custom fields.

Thanks, will take a look right away

**Comment by gwmedia** [comment]
It worked! Thanks!
