### ISSUE TITLE
Upgrade plugin to support v11.00

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#256]
Hi @BenjaminHae 

I almost finished development for v11.00. Changes from v10.00 in frontend:
- random_login_stamp removed
- added email verification to login page
- Use WebCrypto API instead of CryptoJS (and add check for web browser support check)

But I found the web browser plugin does not work out of box. Could you check?

The demo site has been upgraded to v11.00 so you can use this for test: https://phppasswordmanager.sourceforge.io/

**Comment by BenjaminHae** [comment]
I probably also need to replace the algorithms with WebCrypto.

But: Is the output of WebCrypto strictly the same as in CryptoJS? (I guess not) Otherwise migrating directly to the new version is not possible and that would force everyone using the plugin to upgrade. (maybe I could implement a switch, but that's a lot of overhead)

**Comment by zeruniverse** [comment]
Yes. If you use my library, it’s strictly the same. I tested 1000 random
strings / salts

**Comment by zeruniverse** [comment]
CryptoJS uses 500 iterations PBKDF2 and is far lower than NIST recommended
1e4. I think you want users to migrate anyway because the old method will
no longer be safe in near future. The current v11 implementation uses 1e6
iterations.

**Comment by zeruniverse** [comment]
Moved to https://github.com/BenjaminHae/PwChromeExtension/issues/44
