### ISSUE TITLE
what is the password

### ISSUE THREAD

**Issue by kingwenw** [zeruniverse/Password-Manager#262]
hello ,I'm a big fan of yours. 
I really like this password management system.
But I had a problem with deployment.
The password entered after the deployment is complete is incorrect.
What should I do.

The version I deployed was 11.01.
Looking forward to your guidance.
The screenshot of encountered problems is as follows

![image](https://user-images.githubusercontent.com/48201226/128791027-f978a1af-a6bd-4cfe-94b4-8d4d487f6bf3.png)

**Comment by zeruniverse** [comment]
Please follow the installation guide here: https://github.com/zeruniverse/Password-Manager/wiki/Installation

from first look of your screenshot, you clearly didn’t do two things:

1. You did not enable HTTPS. HTTPS is required even for 127.0.0.1
2. you should copy whatever in src folder to the server root dir. NOT the entire repo! I.e, the page in your screenshot should be accessed with URL https://127.0.0.1

**Comment by kingwenw** [comment]
firstly:
I really appreciate your guidance
Follow your instructions,
I have now used HTTPS, and copy whatever in SRC folder to the server root dir .
However, the system still prompts me that the password is incorrect.
What should I do
Looking forward to your reply
![image](https://user-images.githubusercontent.com/48201226/128792812-c12a1cae-2e88-406b-a451-3f14cfb5e7a9.png)

**Comment by zeruniverse** [comment]
Hi

I see hostdomain mismatch error. Did you edit config.php as described inside installation guide? In your case, $HOSTDOMAIN should be https://127.0.0.1/

please do not skip any step in the installation guide.

**Comment by kingwenw** [comment]
Thank you very much. I have successfully deployed.
         I like this system very much.         
         I found that the database table was empty when I entered the database file.       
         So I created a new user using the "signup.php" interface
         The new user successfully logs in to the system.
         This is my screenshot
![image](https://user-images.githubusercontent.com/48201226/128803486-28694fee-7219-4428-9a46-f74d27d8cb91.png)

         But I have a new problem
                1.What should I do if I forget my password
                2.I would like to have an administrator user who can see other users
         Could you give me some guidance

**Comment by zeruniverse** [comment]
The password manager is designed so that you can only decrypt things with
your password because if you have a way to recover information without
password, a hacker can as well. That means:

1. If you forget your password, you will lose everything forever. There’s
no way for you to decrypt the stored information without a password. If you
are afraid of losing password, write it down on a paper and put it
somewhere in your house

2. It is impossible. User’s password will only be known by browser and
processed by browser, and the password will not go to the server. That
said, you can’t know another user’s password, and according to my answer to
previous question, you can’t decrypt their information.

Again, the password manager is designed to make your password safe from
attackers/server admins/governments/polices etc. so it is designed in a way
that you can ONLY decrypt info with correct password

**Comment by zeruniverse** [comment]
@kingwenw  if you are satisfied with my answer, please close the bug
