### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#3]
I just stumbled upon your little project. Nice !

I'd like to make some suggestions though which seem rather important to me.
1. Every account needs a text field for write down a description.
2. Also I would suggest another text field with a possible http link
3. The password field itself should be multiline. Mostly I have to remember more than just a 
   password: like 'loginname', 'customer ID', 'a passwort', 'a pin' and so on.
   So I think a simple multiline text field should be enough to make all that possible.
4. Last but not least I think there should be a switch per account to enable/disable the 'Generate new passwort' option. Accounts can have predefined passwords. Ex: Provider passwords which cannot be changed by the user. You would prevent dire mistakes this way.

**Comment by zeruniverse** [comment]
Thank you for your suggestions!

For 4: Yes, the 'Generate new password' option can cause problem. I'll try to find a way to prevent damages caused by mistake. (Maybe keep one history in server) But I don't think the enable/disable feature is needed. You 'disable' this feature as long as you don't click it.

For 1, 2 &3, if you go through my commit history, you'll find I didn't do much on such additional features. My logic is simple - keep sensitive data in password field and all other description in account field. Both fields will be encrypted but the password field will have a stronger encryption. Though they're single line field, you can exactly put [PASSWORD XXXXXXX PIN XXXXXXX] into the password field anyway. I'll finally make those improvements as time goes by but my main focus for now is security. If you really need all those features, LastPass will be a better choice for you.

Actually I wrote this project for my own use. I care more about my password security than those features that make my life easier. The reason I don't use LastPass-like service is that they can recover your account when you forget your login password. This is unsafe to me because it means the company can have your data if they really want. So in my design, forgetting password theoretically means data lost forever and only your browser sees your login password. By the way, those popular online service would be a bigger target for hackers.

In a word, thank you for your suggestions but I'm afraid I won't implement them in the near future.

**Comment by BenjaminHae** [comment]
Would you accept pull requests for simple enhancements where possible security implications would be easy to see?
I mean things like url fields or tagging.

**Comment by zeruniverse** [comment]
Sorry but I can't simply understand why adding those two fields leads to
problems as long as you encrypt them like the account field.

I definitely won't accept any PR which has a negative impact to security.
But as I said, I don't see why URL and tagging would have such impact. If
you think users might input malicious URL, that's their own business.

**Comment by BenjaminHae** [comment]
> Sorry but I can't simply understand why adding those two fields leads to
> problems as long as you encrypt them like the account field.

I think so too. I just wanted to imply that I'm not going to ask for a pull when it's not easy to see that security is not concerned.

So on to work.

**Comment by zeruniverse** [comment]
@nickbe All your requested features are included in v9.0

**Comment by nickbe** [comment]
Hey great - I'll check this out ASAP. 
Thanks :)

**Comment by nickbe** [comment]
Much better now. Thanks again :)

A new suggestion if I might: Let's click on the EntryName and show the completely entry similar to the edit window, but only as nicely formatted text. 

I thik this is what I would use on my mobile most.

**Comment by zeruniverse** [comment]
I'll consider this in future versions

**Comment by zeruniverse** [comment]
@nickbe Please try newly released v9.05

**Comment by nickbe** [comment]
Hey great good. 
Could you make the complete name  clickable? (A link, but not an obviously underlined one),
It would be easier for mobiles this way :)

**Comment by zeruniverse** [comment]
I won't make it clickable because I might need to copy the contents in
account name. I think my implementation is just equivalent.

**Comment by nickbe** [comment]
Well, Very good point!

So what about a more button like design for the view and edit icons. 
I think they're a little bit hard to click on mobiles.

**Comment by zeruniverse** [comment]
Well, it will take too much space if made bigger. I've tested on my phones and I think they are just about the right size.

You can adjust the icon size your self in `password.php` if you really feel it's small
