### ISSUE TITLE
Option to change the users mail adress

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#56]
Mail adresses may change. So I think It's necessary to let the user change his adress and maybe even his username.

-> Why don't you just use the mailadress for login? Mail adresses are unique - but user names are not. And it would simplify things.

**Comment by zeruniverse** [comment]
This is easy to implement. But it's not safe and I don't think people will change email address. You can modify your email in database anyway

**Comment by nickbe** [comment]
Not safe? Why?

**Comment by zeruniverse** [comment]
Sorry. In the version I use, I integrated email verification.

I just took a look at the version on Github. Seems we don't need email at
all. That's a redundant.

**Comment by nickbe** [comment]
So if we could simply enter mail adresses as user names?
Is it possible to change the username? Does that lead to problems?

**Comment by zeruniverse** [comment]
I'll consider remove the email feature. It isn't used anywhere.

**Comment by zeruniverse** [comment]
Ok I took a look at the project. The `email` field was introduced in the first commit 4ea00d2.  And I noticed the first version has the feature of email verification so it's necessary to have an `email` field. But later I removed this feature as I noticed the implementation of sending emails might vary and not all people want this. Meanwhile I put it in [README](https://github.com/zeruniverse/Password-Manager#extentions) as possible extensions.

Yes, I can confirm for current version, the `email` field does nothing. But I think it's better to keep it because then adding `email verification` feature doesn't involve in database change. As for the option to change email address, it seems this is only useful if `email` does something while it actually doesn't. So I won't implement it.
