### ISSUE TITLE
Make password manager databaseless

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#73]
I know I suggested this before, but I'd like to do it anyway :)

My suggestion is to get rid of the mysql database and work purely on flat files. One file for each password entry. At least as an alternative to the current way.

Three advantages:
1. Completely portable even when carrying around on a usb stick. We could even run the whole thing with the simplest PHP internal server. (PHP -S)
2. Moving the whole system and backing up will be extremely easy since we'd only have to zip the complete folder.
3. Many users have a limited amount of mysql databases. It'll give them a chance to use password manager anyway.

Since a typical password database does probably not contain more than few hundred entries speed will be of no concern either.

**Comment by zeruniverse** [comment]
OK, I can give you a full analysis about this issue, so you can see why I don't want to implement it. To be short, this feature is very hard to implement (you can't simply read/write files, you have to do concurrent access control, disk and memory synchronization... just like what you need to consider for implementing a database manager) and the use case is very limited. You can argue there're SQLite / Berkeley DB. But if you can run those database management software, why you can't run MySQL?

Below is a longer analysis:

There're two options for this feature:
- Implement database functions with native PHP, which involves reading files, storing data, etc. This requires significant amount of work. But you can then use a simplest PHP internal server.  
- Use SQLite or Berkeley DB. Then I don't know what's the difference between this option and using MySQL. Since you need to run an additional program (SQLite or Berkeley DB) anyway.

For three advantages mentioned:  
- [1]If you want to run a portable version of password manager, [KeePass](https://sourceforge.net/projects/keepass) might be a better choice. This way you even skip PHP. PHP is rarely installed in PC.    
- [2]To backup the whole system, you only need to backup your data. Because you can always download the program from GitHub. For now, you can simply export CSV or generate a backup file in the Password-Manager. It contains all your data and the recovery process is independent from the config file. Then you can come to GitHub release page and download the version you want to reinstall and then import. So I don't see why you think the backup function currently doesn't let you backup the whole system.  
  If you mean backing up the data for all users, you can still do it with a simple `mysqldump` command.  
  Anyway, to reinstall, you only need to backup **a single file** instead of a zip file. If you, for some reason, must backup the whole folder, you can simply attach the data file into your zip backup.  
- [3]This is the only reason I see why MySQL is not good. However, then we need to substitute MySQL database with either option 1 or 2 mentioned above. Usually, if you only have limited amount of databases, you are running Password-Manager on a WEB-HOSTING, where you don't have ssh access. In this case, running SQLite or Berkeley DB are not possible. So we can only use PHP to implement our own version of database. This involves a lot of work (not only as simple as insert/delete. But requires implementation of B+ tree structure, consistency control, file & memory synchronization) and I definitely don't want to do that.

**Comment by nickbe** [comment]
Well, that's not completely true. At least if we're talking about the same SQLite database:
https://sqlite.org/

SQlite is a PHP extension and not a server side database and you don't need shell access to use it. in fact I never had to do anything when an installation offered me to choose SQLite instead of mySQL.

So far all hosters I know have included it in their PHP installations. It's stable and quite fast and all web applications I know of that are currently using SQlite are basically portable and can indeed be run/moved wherever I want. 

you end up with a simple .sqlite file where all your data is being stored. I think it would be perfect for this application and would help a lot if we could find a simple way to be able to select either SQLite or MySQL. 

btw. Keepass for windows. has corrupted my data when I was using it. That's why I choose this project and I would never go back here. When that happened I was furious. Lately this also happened to a client of mine. Again keepass. It has severe flaws and I don't recomment it to anyone anymore at least not for windows.

**Comment by BenjaminHae** [comment]
I think sqlite is a nice addition but not strictly necessary. Doing so [should be easy ](http://php.net/manual/de/ref.pdo-sqlite.php) maybe you could implement it yourself @nickbe .

I would strongly oppose using files. I once wrote a small address book manager using plain text files - this was not a very good idea.

**Comment by zeruniverse** [comment]
Well. If SQLite works like what you said, it's probably good and easy to
implement. But I never used SQLite before so I can't say for now. And yes,
you don't want to use plain files as making this work smoothly needs too
much work.

**Comment by nickbe** [comment]
No flat file database then :) Got it.

Well as for the SQLite database.... I know the basic mechanics and I also think it's easy to switch if the database you're working with is not too complicated (which I suppose is the case here). But as much as I'd like to see it work with SQLite I'm afraid I don't have the time right now to dig into the password manager sources.

**Comment by zeruniverse** [comment]
Hi @nickbe ,

I did some short research on SQLite. It uses the same query sentence structure as MySQL. To switch from MySQL to SQLite, **you only need to modify the `sqllink()` function in `src/function/sqllink.php`**. Currently it creates a PDO instance with MySQL interface, switching it to SQLite is **all** you need to do. That said, you don't need to know anything about password manager before you can do this. `sqllink()` is the **only place** in the whole project where database connector API is called.

Since you mentioned you know SQLite, I'll leave the implementation to you. You can upload the SQLite version to GitHub under your account if you find it works smoothly and I'll be happy to mention your project in `README` of this project.

I'll close this issue since I don't plan to switch from MySQL to SQLite in my project. You can send me an email if you finally finish implementing SQLite feature and want me to mention it in my project.

**Comment by nickbe** [comment]
Ok I'll do my best and let you review the version when I'm done testing.
You can decide if this should be part of the official release then.
Thanks

**Comment by zeruniverse** [comment]
And for you mentioned, **there is exactly easy way to switch databases**. In the whole project, only `sqllink()` function in `src/function/sqllink.php` is database dependent. That said, as long as your target database uses the standard SQL query, you can switch to that by only editing this function. No matter it's SQLite or MS SQL or anything like this.
