### ISSUE TITLE
Idea for mobiles but also desktops

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#75]
What about if there was an option to upload an image additionally to a password entry.
On mobiles this could trigger the 'select photo/make picture' function. (This happens by default for image uploads on newer phones as far as I know.)

Typical usage would be a very quick way to add simple entries for cards with lots of stuff written on it like certain 'membership cards' or even an id card.

**Comment by zeruniverse** [comment]
This can be implemented by encoding the image with base64 in JS. Then the coding string can be treated as a password string and go to the encryption process. Actually, we can support any binary file by doing base64 encoding. The problem is, whether we want to do it. As this could possibly undermine the security. What do you think? @BenjaminHae

**Comment by BenjaminHae** [comment]
Maybe a custom field where every item contains a `<img alt="Embedded Image" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIA..." />` tag. This way it will be automatically encrypted and nothing on the backend has to be changed. Only problem I see is that as I remember all content is sanitized so html-tags would only be displayed as plain tags. Maybe just save the value of `src` in the field. Doing everything else in js.

But I think pictures aren't necessary in the main project. I don't know what advantage they'd bring in a password manager.

A plugin architecture is totally overkill but this is a good use case ;)

**Comment by nickbe** [comment]
images of credit cards etc. I always keep them in an archive.
When I once lost a german EC card in asia the police asked if I have an exact visual description of my EC card which I couldn't give at the time because I simply couldn't remember. Strage but since that time I always make photos of my cards at home.

**Comment by zeruniverse** [comment]
This reason is not strong enough for a new feature. You can type the number into the program anyway and it won't cost you significantly more time. If we finally decide to implement it, where to put it will be a question.

But we can consider to add a file field, to store something like ssh private key. However, this will make the database much larger than it might be currently.

**Comment by zeruniverse** [comment]
And for the additional file field, you can store image as well

**Comment by zeruniverse** [comment]
Files can't be encrypted with the password related string or you'll have trouble when you want to change password. My design is to assign a permanent key to a certain file. We only encrypt this key

**Comment by zeruniverse** [comment]
Please try the current master branch for the file extension. Note you need to reconstruct the database by importing `initial.sql`.

You can upload file for an entry by click the UP arrow. After upload, you'll see the DOWN arrow which allows you to download the file. All files are encrypted by a permanent key. The key is encrypted as a password string.
