### ISSUE TITLE
Can't login to demo

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#95]
After creating a new account I can't login. After logging in I get redirected to `password.php` and then back to `index.php`.

**Comment by zeruniverse** [comment]
Could you refresh the pages? I edited many files including `index.php`. It might be web cache that causes this problem

**Comment by BenjaminHae** [comment]
Still the same.

**Comment by zeruniverse** [comment]
That's very weird because it works for me. I created a new account in http://phppasswordmanager.sourceforge.net/ and I can successfully login. Could you try to login on Chrome private mode? This way you can completely get rid of cache. If it still doesn't work, could you trace down a little bit? Since I can't reproduce the bug, I can't help...

**Comment by BenjaminHae** [comment]
Private mode worked. Sorry for the confusion.
