### ISSUE TITLE
Integrate google recaptcha

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#98]
Hi ! 
I'm using your amazing tool and I wanted to add the [google recaptcha](https://www.google.com/recaptcha/intro/index.html) on it ! 

As you said in the [Readme](https://github.com/zeruniverse/Password-Manager#extentions), it is supposed to be simple.

So what did I do:
- in `index.php`:
  - `<script src="https://www.google.com/recaptcha/api.js"></script>` with the other scripts
  - `<div class="g-recaptcha" data-sitekey="the_public_key"></div>` just below the password in the html
  - `$.post("check.php",{pwd:String(CryptoJS.SHA512(String(CryptoJS.SHA512(login_sig+user))+"<?php echo $_SESSION['random_login_stamp']; ?>")),  user: user, grr: "<?php echo $_POST['g-recaptcha-response']; ?>"},function(msg){` with the supposed g-recaptcha-response in parameter.
- in `check.php`:
  - I tried to get the variable as the others doing that `$grr=$_POST['grr'];` but this value is always `null`.

I'm not an expert in php and so on, but I think that the value is always `null` (in `index.php` or in `check.php`). But I don't know why. I might think that as the value is `null` when I load the page, it's still remain `null`.

As you said it should be easy, did you have already some work on that ?

Thanks :)

**Comment by zeruniverse** [comment]
(Strange that Github email direct reply doesn't work...)

I did an email verification for my personal use. In check.php, before storing login identity to session, you just check additional info. That's all needed to be done.

Generally I don't provide support for questions like this since I didn't implement Google recaptcha. But from the first look, you did exactly pass a null value since you put a echo $POST on index.php and this page actually does not have any POST value coming in. You should look at google recaptcha API document for details about how to implement it. There's an easy way to check if you pass the right value in, just use chrome and press F12, in developer tool, see what values are passed to check.php. Is the value grr null?

**Comment by Pofilo** [comment]
Okay thanks, you're right !

Have learned a bit more how it works and I had to get the value I wanted doing `var grr = $("#g-recaptcha-response").val();`.

And I don't know about Github email direct reply :/

**Comment by zeruniverse** [comment]
I did an email verification for my personal use.

In check.php, before storing login identity to session, you just check
additional info. That's all needed to be done.

Generally I don't provide support for questions like this since I didn't
implement Google recaptcha. But from the first look, you did exactly pass a
null value since you put a echo $POST on index.php and this page actually
does not have any POST value coming in. You should look at google
recaptcha API document for details about how to implement it. There's an
easy way to check if you pass the right value in, just use chrome and press
F12, in developer tool, see what values are passed to check.php. Is the
value grr null?
